# Generated by Django 3.2.7 on 2021-10-23 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('bets', '0002_bet_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='creation_datetime',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='factor',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='status',
        ),
        migrations.AddField(
            model_name='bet',
            name='currency',
            field=models.CharField(default='RUB', max_length=256, verbose_name='валюта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='games.game', verbose_name='игра'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='round',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
