# Generated by Django 3.2.7 on 2021-10-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_bet_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='factor',
            field=models.PositiveIntegerField(default=1, verbose_name='множитель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('active', 'Активная ставка'), ('win', 'Выигрышная ставка'), ('lose', 'Проигрышная ставка')], default='active', max_length=32, verbose_name='статус'),
        ),
    ]
