# Generated by Django 3.2.7 on 2021-10-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_bet_creatine_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='creatine_datetime',
            new_name='creation_datetime',
        ),
    ]
