# Generated by Django 3.2.7 on 2021-10-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_rename_creatine_datetime_bet_creation_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('active', 'Активная ставка'), ('win', 'Выигрышная ставка'), ('loose', 'Проигрышная ставка')], default='active', max_length=32, verbose_name='статус'),
        ),
    ]
