# Generated by Django 3.2.7 on 2021-10-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='размер депозита')),
                ('currency', models.CharField(max_length=256)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
            ],
        ),
    ]
