# Generated by Django 3.2.7 on 2021-10-18 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='размер снятия')),
                ('currency', models.CharField(max_length=256)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to='players.player', verbose_name='игрок')),
            ],
        ),
    ]
