# Generated by Django 3.2.7 on 2021-10-18 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ms', models.PositiveIntegerField(verbose_name='id в системе мерчанта')),
                ('private_token', models.CharField(max_length=256, verbose_name='публичный токен')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL, verbose_name='мерчант')),
            ],
        ),
    ]
