# Generated by Django 3.2.7 on 2021-10-02 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=256, verbose_name='никнейм')),
                ('token', models.CharField(max_length=256, verbose_name='токен')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='баланс')),
                ('active_bets', models.PositiveIntegerField(default=0, verbose_name='количество активных ставок')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='providers.provider', verbose_name='провайдер')),
            ],
        ),
    ]
